[profile.default]
src = "src"
out = "out"
libs = ["lib"]


optimizer = true
optimizer_runs = 9999

via_ir = true

remappings = [
  "@solady=lib/solady/",
  "@forge=lib/forge-std/src/",
  '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
  '@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts'
]
[rpc_endpoints]
main = "https://eth-mainnet.g.alchemy.com/v2/KywLaq2zlVzePOhip0BY3U8ztfHkYDmo"